### ISSUE TITLE
Logs in Kibana broken when using newer versions of NLog

### ISSUE THREAD

**Issue by piotr-wieruszewski** [justeat/NLog.StructuredLogging.Json#54] opened 2017-05-04 11:38 UTC
When using certain combination of *NLog* and *Nlog.StructuredLogging.Json* versions the logs in *Kibana* contain only properties with suffix `@`. See the example screenshot below where the app version in the bottom (1.0.0.41) - with *Nlog 4.4.3* and *Nlog.StructuredLogging.Json 1.0.78* - has missing fields like  `Message`, `Level`, `ProcessId`, then above (1.0.0.42)  when other combination of versions used in the same app, then it is working:
![image](https://cloud.githubusercontent.com/assets/6325279/25701090/b1ed599e-30c2-11e7-9ba8-a44895e251d6.png)
Here is the table containing the combination of different versions (*Newtonsoft.Json 9.0.1* was used) and whether it works or not:
*NLog* | *Nlog.StructuredLogging.Json* | Is working?
4.4.3 | 1.0.78 | **No** (also tested with *Newtonsoft* 10.0.2)
4.4.8 | 1.0.78 | **No**
4.4.3 | 1.0.68 | **No**
4.4.1 | 1.0.68 | Yes
4.4.5 | 1.0.58 | **No**
4.3.11 | 1.0.58 | Yes

**Comment by AnthonySteele** [comment] 2017-05-04 11:54
That's odd. We haven't seen the same. So it looks like the issue is with all nlog versions after 4.4.1?

The thing to do is to get StructuredLogging.Json to log to file, and inspect the output. Each line should be a well-formed json object. if it's not, then problem is in the Nlog/StructuredLogging.Json/Newtonsoft part. If it is well-formed then the issue is in the log transport to kibana - we use NXLog for that.

**Comment by AnthonySteele** [comment] 2017-05-04 13:54
The `nlog.config` file contained `<layout xsi:type="FlattenedJsonLayout"/>` and not ` layout="${structuredlogging.json}"`, [see the example](https://github.com/justeat/NLog.StructuredLogging.Json/blob/master/Examples/nlog.config#L15). 

The json generated did not have quotations around the values in the key-value pairs, so was not valid.
e.g. it contained `{"TimeStamp":2017-05-04T13:13:48.599Z,"Level":Debug, ...`  but should have been `{"TimeStamp":"2017-05-04T13:13:48.599Z","Level":"Debug", ... `

The immediate fix was to use  ` layout="${structuredlogging.json}"`, but the other configuration should not fail in this way either.

**Comment by AnthonySteele** [comment] 2017-05-15 13:07
Fixed in [version 1.0.116](https://www.nuget.org/packages/NLog.StructuredLogging.Json/1.0.116) or later

**Closed as completed by AnthonySteele** 2017-05-15 13:07 UTC
Labels: bug
